# Generated by Django 5.2.1 on 2025-07-05 06:28

import ckeditor.fields
import django.db.models.deletion
import forms.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TaxForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_number', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=300)),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('pdf_file', models.FileField(blank=True, help_text='Upload PDF version of the form', null=True, upload_to=forms.models.form_upload_path)),
                ('word_file', models.FileField(blank=True, help_text='Upload Word version of the form', null=True, upload_to=forms.models.form_upload_path)),
                ('excel_file', models.FileField(blank=True, help_text='Upload Excel version of the form', null=True, upload_to=forms.models.form_upload_path)),
                ('pdf_size', models.PositiveIntegerField(blank=True, null=True)),
                ('word_size', models.PositiveIntegerField(blank=True, null=True)),
                ('excel_size', models.PositiveIntegerField(blank=True, null=True)),
                ('file_type', models.CharField(choices=[('pdf', 'PDF'), ('word', 'Word Document'), ('excel', 'Excel'), ('multiple', 'Multiple Formats'), ('other', 'Other')], default='pdf', max_length=20)),
                ('external_url', models.URLField(blank=True, help_text='Direct URL to the form if not uploading files', null=True)),
                ('assessment_year', models.CharField(blank=True, max_length=20, null=True)),
                ('financial_year', models.CharField(blank=True, max_length=20, null=True)),
                ('meta_title', models.CharField(blank=True, max_length=200, null=True)),
                ('meta_description', models.TextField(blank=True, max_length=500, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('pdf_download_count', models.PositiveIntegerField(default=0)),
                ('word_download_count', models.PositiveIntegerField(default=0)),
                ('excel_download_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forms', to='forms.category')),
            ],
            options={
                'ordering': ['order', 'form_number'],
                'unique_together': {('form_number', 'assessment_year')},
            },
        ),
        migrations.CreateModel(
            name='FormLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('url', models.URLField()),
                ('link_type', models.CharField(choices=[('official', 'Official Website'), ('guide', 'How-to Guide'), ('instruction', 'Instructions'), ('sample', 'Sample Form'), ('related', 'Related Form'), ('pdf_alt', 'Alternative PDF Link'), ('word_alt', 'Alternative Word Link'), ('excel_alt', 'Alternative Excel Link'), ('other', 'Other')], default='other', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_links', to='forms.taxform')),
            ],
            options={
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='FormFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=forms.models.form_upload_path)),
                ('file_type', models.CharField(choices=[('pdf', 'PDF'), ('word', 'Word Document'), ('excel', 'Excel Spreadsheet'), ('txt', 'Text File'), ('xml', 'XML File'), ('zip', 'ZIP Archive'), ('other', 'Other')], max_length=20)),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('file_size', models.PositiveIntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_files', to='forms.taxform')),
            ],
            options={
                'ordering': ['order', 'file_name'],
            },
        ),
        migrations.CreateModel(
            name='FormDownload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('download_type', models.CharField(choices=[('pdf', 'PDF Download'), ('word', 'Word Download'), ('excel', 'Excel Download'), ('external', 'External Link')], default='pdf', max_length=20)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('downloaded_at', models.DateTimeField(auto_now_add=True)),
                ('referrer', models.URLField(blank=True, null=True)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downloads', to='forms.taxform')),
            ],
            options={
                'ordering': ['-downloaded_at'],
            },
        ),
    ]
