# Generated by Django 5.2.1 on 2025-06-30 06:12

import django.db.models.deletion
import forms.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taxform',
            old_name='file_size',
            new_name='excel_size',
        ),
        migrations.RemoveField(
            model_name='taxform',
            name='form_file',
        ),
        migrations.AddField(
            model_name='formdownload',
            name='download_type',
            field=models.CharField(choices=[('pdf', 'PDF Download'), ('word', 'Word Download'), ('excel', 'Excel Download'), ('external', 'External Link')], default='pdf', max_length=20),
        ),
        migrations.AddField(
            model_name='taxform',
            name='excel_download_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='taxform',
            name='excel_file',
            field=models.FileField(blank=True, help_text='Upload Excel version of the form', null=True, upload_to=forms.models.form_upload_path),
        ),
        migrations.AddField(
            model_name='taxform',
            name='pdf_download_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='taxform',
            name='pdf_file',
            field=models.FileField(blank=True, help_text='Upload PDF version of the form', null=True, upload_to=forms.models.form_upload_path),
        ),
        migrations.AddField(
            model_name='taxform',
            name='pdf_size',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taxform',
            name='word_download_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='taxform',
            name='word_file',
            field=models.FileField(blank=True, help_text='Upload Word version of the form', null=True, upload_to=forms.models.form_upload_path),
        ),
        migrations.AddField(
            model_name='taxform',
            name='word_size',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='formlink',
            name='link_type',
            field=models.CharField(choices=[('official', 'Official Website'), ('guide', 'How-to Guide'), ('instruction', 'Instructions'), ('sample', 'Sample Form'), ('related', 'Related Form'), ('pdf_alt', 'Alternative PDF Link'), ('word_alt', 'Alternative Word Link'), ('excel_alt', 'Alternative Excel Link'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AlterField(
            model_name='taxform',
            name='external_url',
            field=models.URLField(blank=True, help_text='Direct URL to the form if not uploading files', null=True),
        ),
        migrations.AlterField(
            model_name='taxform',
            name='file_type',
            field=models.CharField(choices=[('pdf', 'PDF'), ('word', 'Word Document'), ('excel', 'Excel'), ('multiple', 'Multiple Formats'), ('other', 'Other')], default='pdf', max_length=20),
        ),
        migrations.CreateModel(
            name='FormFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=forms.models.form_upload_path)),
                ('file_type', models.CharField(choices=[('pdf', 'PDF'), ('word', 'Word Document'), ('excel', 'Excel Spreadsheet'), ('txt', 'Text File'), ('xml', 'XML File'), ('zip', 'ZIP Archive'), ('other', 'Other')], max_length=20)),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('file_size', models.PositiveIntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_files', to='forms.taxform')),
            ],
            options={
                'ordering': ['order', 'file_name'],
            },
        ),
    ]
