# Generated by Django 5.2.1 on 2025-06-29 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='act',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='acts', to='acts.category'),
            preserve_default=False,
        ),
    ]
