# Generated by Django 5.2.1 on 2025-06-29 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acts', '0002_act_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='act',
            name='category',
        ),
    ]
