# Generated by Django 5.2.1 on 2025-06-29 07:02

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('rbi_sebi', 'RBI SEBI'), ('notification', 'Notification'), ('circular', 'Circular'), ('income_tax', 'Income Tax'), ('service_tax', 'Service Tax'), ('central_sales_tax', 'Central Sales Tax'), ('excise_matters', 'Excise Matters'), ('customs', 'Customs'), ('company_law', 'Company Law'), ('labour_laws', 'Labour Laws'), ('fema', 'FEMA'), ('llp_act_2008', 'The LLP Act 2008'), ('accounting_standard', 'Accounting Standard (INDAS)'), ('others', 'Others'), ('gst', 'GST'), ('igst', 'IGST'), ('utgst', 'UTGST'), ('compensation_cess', 'Compensation Cess'), ('ibc_regulation', 'IBC Regulation'), ('vat', 'VAT'), ('delhi_vat', 'Delhi VAT'), ('maharashtra_vat', 'Maharashtra VAT'), ('gujarat_vat', 'Gujarat VAT'), ('telangana_vat', 'Telangana VAT'), ('tamil_nadu_vat', 'Tamil Nadu VAT'), ('karnataka_vat', 'Karnataka VAT'), ('west_bengal_vat', 'West Bengal VAT'), ('rajasthan_vat', 'Rajasthan VAT'), ('uttar_pradesh_vat', 'Uttar Pradesh VAT'), ('punjab_vat', 'Punjab VAT')], max_length=100, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='bulletins.notificationcategory')),
            ],
            options={
                'verbose_name_plural': 'Notification Categories',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', ckeditor.fields.RichTextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='bulletins.notificationcategory')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
