# Generated by Django 5.2.4 on 2025-07-14 06:06

import bulletins.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletins', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='pdf_file',
            field=models.FileField(blank=True, help_text='Upload PDF file (optional)', null=True, upload_to=bulletins.models.notification_pdf_upload_path),
        ),
    ]
