# Generated by Django 5.2.4 on 2025-07-09 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=200, default='temp-slug'),
            preserve_default=False,
        ),
    ]
